version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: viegym_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: viegym
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "5433:5432"   
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: viegym_redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: ./viegymapp
    container_name: viegym_backend
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/viegym
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8080:8080"

  frontend:
    build: ./viegymfe
    container_name: viegym_frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  pgdata:
