spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/viegym
    username: postgres
    password: 123456

  jpa:
    hibernate:
      "ddl-auto": update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080
  error:
    include-message: always
